export const woodData = [
    {
        textures: "textures/blocks/log_oak",
        name: "Oak Log",
        cost: 256,
        sell: 32,
        data: 0,
        item: "log",
    },
    {
        textures: "textures/blocks/planks_oak",
        name: "Oak Plank",
        cost: 64,
        sell: 16,
        data: 0,
        item: "planks",
    },
    {
        textures: "textures/blocks/log_spruce",
        name: "Spruce Log",
        cost: 256,
        sell: 32,
        data: 1,
        item: "log",
    },
    {
        textures: "textures/blocks/planks_spruce",
        name: "Spruce Plank",
        cost: 64,
        sell: 16,
        data: 1,
        item: "planks",
    },
    {
        textures: "textures/blocks/log_birch",
        name: "Birch Log",
        cost: 256,
        sell: 32,
        data: 2,
        item: "log",
    },
    {
        textures: "textures/blocks/planks_birch",
        name: "Birch Plank",
        cost: 64,
        sell: 16,
        data: 2,
        item: "planks",
    },
    {
        textures: "textures/blocks/log_jungle",
        name: "Jungle Log",
        cost: 256,
        sell: 32,
        data: 3,
        item: "log",
    },
    {
        textures: "textures/blocks/planks_jungle",
        name: "Jungle Plank",
        cost: 64,
        sell: 16,
        data: 3,
        item: "planks",
    },
    {
        textures: "textures/blocks/log_acacia",
        name: "Acacia Log",
        cost: 256,
        sell: 32,
        data: 0,
        item: "log2",
    },
    {
        textures: "textures/blocks/planks_acacia",
        name: "Acacia Plank",
        cost: 64,
        sell: 16,
        data: 4,
        item: "planks",
    },
    {
        textures: "textures/blocks/log_big_oak",
        name: "Dark Oak Log",
        cost: 256,
        sell: 32,
        data: 1,
        item: "log2",
    },
    {
        textures: "textures/blocks/planks_big_oak",
        name: "Dark Oak Plank",
        cost: 64,
        sell: 16,
        data: 5,
        item: "planks",
    },
    {
        textures: "textures/blocks/mangrove_log_side",
        name: "Mangrove Log",
        cost: 256,
        sell: 32,
        data: 0,
        item: "mangrove_log",
    },
    {
        textures: "textures/blocks/mangrove_planks",
        name: "Mangrove Plank",
        cost: 64,
        sell: 16,
        data: 0,
        item: "mangrove_planks",
    },
    {
        textures: "textures/blocks/huge_fungus/crimson_log_top",
        name: "Crimson Stem",
        cost: 256,
        sell: 32,
        data: 0,
        item: "crimson_stem",
    },
    {
        textures: "textures/blocks/huge_fungus/crimson_planks",
        name: "Crimson Plank",
        cost: 64,
        sell: 16,
        data: 0,
        item: "crimson_planks",
    },
    {
        textures: "textures/blocks/huge_fungus/warped_stem_top",
        name: "Warped Stem",
        cost: 256,
        sell: 32,
        data: 0,
        item: "warped_stem",
    },
    {
        textures: "textures/blocks/huge_fungus/warped_planks",
        name: "Warped Plank",
        cost: 64,
        sell: 16,
        data: 0,
        item: "warped_planks",
    },
    {
        textures: "textures/blocks/bamboo_stem",
        name: "Bamboo Planks",
        cost: 64,
        sell: 32,
        data: 0,
        item: "bamboo_planks",
    },
];

export const stoneData = [
    {
        textures: "textures/blocks/brick",
        name: "Brick Block",
        cost: 64,
        sell: 16,
        data: 0,
        item: "brick_block",
    },
    {
        textures: "textures/blocks/stone",
        name: "Stone",
        cost: 128,
        sell: 32,
        data: 0,
        item: "stone",
    },
    {
        textures: "textures/blocks/gravel",
        name: "Gravel",
        cost: 96,
        sell: 16,
        data: 0,
        item: "gravel",
    },
    {
        textures: "textures/blocks/cobblestone",
        name: "Cobblestone",
        cost: 96,
        sell: 16,
        data: 0,
        item: "cobblestone",
    },
    {
        textures: "textures/blocks/cobblestone_mossy",
        name: "Mossy Cobblestone",
        cost: 96,
        sell: 16,
        data: 0,
        item: "mossy_cobblestone",
    },
    {
        textures: "textures/blocks/stone_slab_top",
        name: "Smooth Stone",
        cost: 160,
        sell: 16,
        data: 0,
        item: "smooth_stone",
    },
    {
        textures: "textures/blocks/stonebrick",
        name: "Stonebrick",
        cost: 256,
        sell: 32,
        data: 0,
        item: "stonebrick",
    },
    {
        textures: "textures/blocks/stonebrick_mossy",
        name: "Mossy Stonebrick",
        cost: 256,
        sell: 32,
        data: 0,
        item: "mossy_stonebrick",
    },
    {
        textures: "textures/blocks/stone_granite",
        name: "Granite",
        cost: 128,
        sell: 16,
        data: 1,
        item: "stone",
    },
    {
        textures: "textures/blocks/stone_diorite",
        name: "Diorite",
        cost: 128,
        sell: 16,
        data: 3,
        item: "stone",
    },
    {
        textures: "textures/blocks/stone_andesite",
        name: "Andesite",
        cost: 128,
        sell: 16,
        data: 5,
        item: "stone",
    },
    {
        textures: "textures/blocks/deepslate/deepslate",
        name: "Deepslate",
        cost: 128,
        sell: 16,
        data: 0,
        item: "deepslate",
    },
    {
        textures: "textures/blocks/deepslate/cobbled_deepslate",
        name: "Cobbled Deepslate",
        cost: 128,
        sell: 16,
        data: 0,
        item: "cobbled_deepslate",
    },
    {
        textures: "textures/blocks/deepslate/deepslate_bricks",
        name: "Deepslate Brick",
        cost: 128,
        sell: 16,
        data: 0,
        item: "deepslate_bricks",
    },
    {
        textures: "textures/blocks/deepslate/deepslate_tiles",
        name: "Deepslate Tiles",
        cost: 128,
        sell: 16,
        data: 0,
        item: "deepslate_tiles",
    },
];

export const glassData = [
    {
        textures: "textures/blocks/glass",
        name: "Natural Glass",
        cost: 96,
        sell: 16,
        data: 0,
        item: "glass",
    },
    {
        textures: "textures/blocks/glass_white",
        name: "White Glass",
        cost: 96,
        sell: 16,
        data: 0,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_orange",
        name: "Orange Glass",
        cost: 96,
        sell: 16,
        data: 1,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_magenta",
        name: "Magenta Glass",
        cost: 96,
        sell: 16,
        data: 2,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_light_blue",
        name: "Light Blue Glass",
        cost: 96,
        sell: 16,
        data: 3,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_yellow",
        name: "Yellow Glass",
        cost: 96,
        sell: 16,
        data: 4,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_lime",
        name: "Lime Glass",
        cost: 96,
        sell: 16,
        data: 5,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_pink",
        name: "Pink Glass",
        cost: 96,
        sell: 16,
        data: 6,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_gray",
        name: "Gray Glass",
        cost: 96,
        sell: 16,
        data: 7,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_silver",
        name: "Light Gray Glass",
        cost: 96,
        sell: 16,
        data: 8,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_cyan",
        name: "Cyan Glass",
        cost: 96,
        sell: 16,
        data: 9,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_purple",
        name: "Purple Glass",
        cost: 96,
        sell: 16,
        data: 10,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_blue",
        name: "Blue Glass",
        cost: 96,
        sell: 16,
        data: 11,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_brown",
        name: "Brown Glass",
        cost: 96,
        sell: 16,
        data: 12,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_green",
        name: "Green Glass",
        cost: 96,
        sell: 16,
        data: 13,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_red",
        name: "Red Glass",
        cost: 96,
        sell: 16,
        data: 14,
        item: "stained_glass",
    },
    {
        textures: "textures/blocks/glass_black",
        name: "Black Glass",
        cost: 96,
        sell: 16,
        data: 15,
        item: "stained_glass",
    },
];

export const woolData = [
    {
        textures: "textures/blocks/wool_colored_white",
        name: "White Wool",
        cost: 96,
        sell: 16,
        data: 0,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_orange",
        name: "Orange Wool",
        cost: 96,
        sell: 16,
        data: 1,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_magenta",
        name: "Magenta Wool",
        cost: 96,
        sell: 16,
        data: 2,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_light_blue",
        name: "Light Blue Wool",
        cost: 96,
        sell: 16,
        data: 3,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_yellow",
        name: "Yellow Wool",
        cost: 96,
        sell: 16,
        data: 4,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_lime",
        name: "Lime Wool",
        cost: 96,
        sell: 16,
        data: 5,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_pink",
        name: "Pink Wool",
        cost: 96,
        sell: 16,
        data: 6,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_gray",
        name: "Gray Wool",
        cost: 96,
        sell: 16,
        data: 7,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_silver",
        name: "Light Gray Wool",
        cost: 96,
        sell: 16,
        data: 8,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_cyan",
        name: "Cyan Wool",
        cost: 96,
        sell: 16,
        data: 9,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_purple",
        name: "Purple Wool",
        cost: 96,
        sell: 16,
        data: 10,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_blue",
        name: "Blue Wool",
        cost: 96,
        sell: 16,
        data: 11,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_brown",
        name: "Brown Wool",
        cost: 96,
        sell: 16,
        data: 12,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_green",
        name: "Green Wool",
        cost: 96,
        sell: 16,
        data: 13,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_red",
        name: "Red Wool",
        cost: 96,
        sell: 16,
        data: 14,
        item: "wool",
    },
    {
        textures: "textures/blocks/wool_colored_black",
        name: "Black Wool",
        cost: 96,
        sell: 16,
        data: 15,
        item: "wool",
    },
];

export const concreteData = [
    {
        textures: "textures/blocks/concrete_white",
        name: "White Concrete",
        cost: 128,
        sell: 16,
        data: 0,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_orange",
        name: "Orange Concrete",
        cost: 128,
        sell: 16,
        data: 1,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_magenta",
        name: "Magenta Concrete",
        cost: 128,
        sell: 16,
        data: 2,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_light_blue",
        name: "Light Blue Concrete",
        cost: 128,
        sell: 16,
        data: 3,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_yellow",
        name: "Yellow Concrete",
        cost: 128,
        sell: 16,
        data: 4,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_lime",
        name: "Lime Concrete",
        cost: 128,
        sell: 16,
        data: 5,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_pink",
        name: "Pink Concrete",
        cost: 128,
        sell: 16,
        data: 6,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_gray",
        name: "Gray Concrete",
        cost: 128,
        sell: 16,
        data: 7,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_silver",
        name: "Light Gray Concrete",
        cost: 128,
        sell: 16,
        data: 8,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_cyan",
        name: "Cyan Concrete",
        cost: 128,
        sell: 16,
        data: 9,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_purple",
        name: "Purple Concrete",
        cost: 128,
        sell: 16,
        data: 10,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_blue",
        name: "Blue Concrete",
        cost: 128,
        sell: 16,
        data: 11,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_brown",
        name: "Brown Concrete",
        cost: 128,
        sell: 16,
        data: 12,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_green",
        name: "Green Concrete",
        cost: 128,
        sell: 16,
        data: 13,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_red",
        name: "Red Concrete",
        cost: 128,
        sell: 16,
        data: 14,
        item: "concrete",
    },
    {
        textures: "textures/blocks/concrete_black",
        name: "Black Concrete",
        cost: 128,
        sell: 16,
        data: 15,
        item: "concrete",
    },
];

export const terracottaData = [
    {
        textures: "textures/blocks/hardened_clay_stained_white",
        name: "White Terracotta",
        cost: 128,
        sell: 16,
        data: 0,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_orange",
        name: "Orange Terracotta",
        cost: 128,
        sell: 16,
        data: 1,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_magenta",
        name: "Magenta Terracotta",
        cost: 128,
        sell: 16,
        data: 2,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_light_blue",
        name: "Light Blue Terracotta",
        cost: 128,
        sell: 16,
        data: 3,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_yellow",
        name: "Yellow Terracotta",
        cost: 128,
        sell: 16,
        data: 4,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_lime",
        name: "Lime Terracotta",
        cost: 128,
        sell: 16,
        data: 5,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_pink",
        name: "Pink Terracotta",
        cost: 128,
        sell: 16,
        data: 6,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_gray",
        name: "Gray Terracotta",
        cost: 128,
        sell: 16,
        data: 7,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_silver",
        name: "Light Gray Terracotta",
        cost: 128,
        sell: 16,
        data: 8,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_cyan",
        name: "Cyan Terracotta",
        cost: 128,
        sell: 16,
        data: 9,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_purple",
        name: "Purple Terracotta",
        cost: 128,
        sell: 16,
        data: 10,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_blue",
        name: "Blue Terracotta",
        cost: 128,
        sell: 16,
        data: 11,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_brown",
        name: "Brown Terracotta",
        cost: 128,
        sell: 16,
        data: 12,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_green",
        name: "Green Terracotta",
        cost: 128,
        sell: 16,
        data: 13,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_red",
        name: "Red Terracotta",
        cost: 128,
        sell: 16,
        data: 14,
        item: "stained_hardened_clay",
    },
    {
        textures: "textures/blocks/hardened_clay_stained_black",
        name: "Black Terracotta",
        cost: 128,
        sell: 16,
        data: 15,
        item: "stained_hardened_clay",
    },
];
