export const netherData = [
    {
        textures: "textures/blocks/netherrack",
        name: "Netherrack",
        cost: 32,
        sell: 4,
        data: 0,
        item: "netherrack",
    },
    {
        textures: "textures/blocks/crimson_nylium_side",
        name: "Crimson Nylium",
        cost: 32,
        sell: 8,
        data: 0,
        item: "crimson_nylium",
    },
    {
        textures: "textures/blocks/warped_nylium_side",
        name: "Warped Nylium",
        cost: 32,
        sell: 8,
        data: 0,
        item: "warped_nylium",
    },
    {
        textures: "textures/blocks/nether_wart_block",
        name: "Nether Wart Block",
        cost: 32,
        sell: 8,
        data: 0,
        item: "nether_wart_block",
    },
    {
        textures: "textures/blocks/warped_wart_block",
        name: "Warped Wart Block",
        cost: 32,
        sell: 8,
        data: 0,
        item: "warped_wart_block",
    },
    {
        textures: "textures/blocks/weeping_vines_base",
        name: "Weeping Vines",
        cost: 32,
        sell: 4,
        data: 0,
        item: "weeping_vines",
    },
    {
        textures: "textures/blocks/twisting_vines_base",
        name: "Twisting Vines",
        cost: 32,
        sell: 4,
        data: 0,
        item: "twisting_vines",
    },
    {
        textures: "textures/blocks/shroomlight",
        name: "Shroomlight",
        cost: 48,
        sell: 4,
        data: 0,
        item: "shroomlight",
    },
    {
        textures: "textures/blocks/soul_sand",
        name: "Soul Sand",
        cost: 64,
        sell: 4,
        data: 0,
        item: "soul_sand",
    },
    {
        textures: "textures/blocks/soul_soil",
        name: "Soul Soil",
        cost: 64,
        sell: 4,
        data: 0,
        item: "soul_soil",
    },
    {
        textures: "textures/blocks/magma",
        name: "Magma",
        cost: 64,
        sell: 4,
        data: 0,
        item: "magma",
    },
    {
        textures: "textures/blocks/blackstone",
        name: "Blackstone",
        cost: 64,
        sell: 4,
        data: 0,
        item: "blackstone",
    },
    {
        textures: "textures/blocks/basalt_top",
        name: "Basalt",
        cost: 64,
        sell: 4,
        data: 0,
        item: "basalt",
    },
    {
        textures: "textures/blocks/smooth_basalt",
        name: "Smooth Basalt",
        cost: 64,
        sell: 4,
        data: 0,
        item: "smooth_basalt",
    },
];

export const overworldData = [
    {
        textures: "textures/blocks/grass_side_carried",
        name: "Grass Block",
        cost: 128,
        sell: 16,
        data: 0,
        item: "grass",
    },
    {
        textures: "textures/blocks/dirt",
        name: "Dirt",
        cost: 64,
        sell: 8,
        data: 0,
        item: "dirt",
    },
    {
        textures: "textures/blocks/grass_path_side",
        name: "Dirt Path",
        cost: 64,
        sell: 8,
        data: 0,
        item: "dirt_path",
    },
    {
        textures: "textures/blocks/coarse_dirt",
        name: "Coarse Dirt",
        cost: 96,
        sell: 8,
        data: 1,
        item: "dirt",
    },
    {
        textures: "textures/blocks/dirt_with_roots",
        name: "Rooted Dirt",
        cost: 64,
        sell: 8,
        data: 0,
        item: "dirt_with_roots",
    },
    {
        textures: "textures/blocks/dirt_podzol_side",
        name: "Podzol",
        cost: 64,
        sell: 8,
        data: 0,
        item: "podzol",
    },
    {
        textures: "textures/blocks/mycelium_side",
        name: "Mycelium",
        cost: 128,
        sell: 8,
        data: 0,
        item: "mycelium",
    },
    {
        textures: "textures/blocks/mud",
        name: "Mud",
        cost: 64,
        sell: 8,
        data: 0,
        item: "mud",
    },
    {
        textures: "textures/blocks/mud_bricks",
        name: "Mud Brick",
        cost: 64,
        sell: 8,
        data: 0,
        item: "mud_brick",
    },
    {
        textures: "textures/blocks/packed_mud",
        name: "Packed Mud",
        cost: 64,
        sell: 8,
        data: 0,
        item: "packed_mud",
    },
    {
        textures: "textures/blocks/clay",
        name: "Clay",
        cost: 64,
        sell: 8,
        data: 0,
        item: "clay",
    },
    {
        textures: "textures/blocks/sand",
        name: "Sand",
        cost: 96,
        sell: 8,
        data: 0,
        item: "sand",
    },
    {
        textures: "textures/blocks/sandstone_top",
        name: "Sandstone",
        cost: 64,
        sell: 8,
        data: 0,
        item: "sandstone",
    },
    {
        textures: "textures/blocks/red_sand",
        name: "Red Sand",
        cost: 96,
        sell: 8,
        data: 0,
        item: "red_sand",
    },
    {
        textures: "textures/blocks/red_sandstone_top",
        name: "Red Sandstone",
        cost: 64,
        sell: 8,
        data: 0,
        item: "red_sandstone",
    },
    {
        textures: "textures/blocks/amethyst_block",
        name: "Amethyst Block",
        cost: 196,
        sell: 32,
        data: 0,
        item: "amethyst_block",
    },
    {
        textures: "textures/blocks/calcite",
        name: "Calcite",
        cost: 96,
        sell: 8,
        data: 0,
        item: "",
    },
    {
        textures: "textures/blocks/tuff",
        name: "Tuff",
        cost: 64,
        sell: 8,
        data: 0,
        item: "tuff",
    },
    {
        textures: "textures/blocks/dripstone_block",
        name: "Dripstone",
        cost: 64,
        sell: 8,
        data: 0,
        item: "dripstone_block",
    },
    {
        textures: "textures/blocks/pointed_dripstone_down_tip",
        name: "Pointed Dripstone",
        cost: 96,
        sell: 8,
        data: 0,
        item: "pointed_dripstone",
    },
    {
        textures: "textures/blocks/moss_block",
        name: "Moss Block",
        cost: 64,
        sell: 8,
        data: 0,
        item: "moss_block",
    },
    {
        textures: "textures/blocks/ice",
        name: "Ice",
        cost: 64,
        sell: 8,
        data: 0,
        item: "ice",
    },
    {
        textures: "textures/blocks/ice_packed",
        name: "Packed Ice",
        cost: 64,
        sell: 8,
        data: 0,
        item: "packed_ice",
    },
    {
        textures: "textures/blocks/blue_ice",
        name: "Blue Ice",
        cost: 64,
        sell: 8,
        data: 0,
        item: "blue_ice",
    },
    {
        textures: "textures/blocks/snow",
        name: "Snow Block",
        cost: 64,
        sell: 8,
        data: 0,
        item: "snow",
    },
    {
        textures: "textures/blocks/obsidian",
        name: "Obsidian",
        cost: 256,
        sell: 32,
        data: 0,
        item: "obsidian",
    },
    {
        textures: "textures/blocks/crying_obsidian",
        name: "Crying Obsidian",
        cost: 196,
        sell: 16,
        data: 0,
        item: "crying_obsidian",
    },
    {
        textures: "textures/blocks/prismarine_bricks",
        name: "Prismarine",
        cost: 128,
        sell: 8,
        data: 0,
        item: "prismarine",
    },
    {
        textures: "textures/blocks/sponge",
        name: "Sponge",
        cost: 128,
        sell: 8,
        data: 0,
        item: "sponge",
    },
];

export const theEndData = [
    {
        textures: "textures/blocks/end_stone",
        name: "End Stone",
        cost: 48,
        sell: 4,
        data: 0,
        item: "end_stone",
    },
    {
        textures: "textures/blocks/obsidian",
        name: "Obsidian",
        cost: 256,
        sell: 32,
        data: 0,
        item: "obsidian",
    },
    {
        textures: "textures/blocks/purpur_block",
        name: "Purpur Block",
        cost: 64,
        sell: 8,
        data: 0,
        item: "purpur_block",
    },
    {
        textures: "textures/blocks/purpur_pillar",
        name: "Purpur Pillar",
        cost: 64,
        sell: 8,
        data: 2,
        item: "purpur_block",
    },
    {
        textures: "textures/blocks/chorus_flower",
        name: "Chorus Flower",
        cost: 64,
        sell: 8,
        data: 0,
        item: "chorus_flower",
    },
    {
        textures: "textures/blocks/chorus_plant",
        name: "Chorus Plant",
        cost: 64,
        sell: 8,
        data: 0,
        item: "chorus_plant",
    },
];
