export const cookedMeatData = [
    {
        textures: "textures/items/chicken_cooked.png",
        name: "Cooked Chicken",
        cost: 96,
        data: 0,
        item: "cooked_chicken",
    },
    {
        textures: "textures/items/porkchop_cooked.png",
        name: "Cooked Porkchop",
        cost: 96,
        data: 0,
        item: "cooked_porkchop",
    },
    {
        textures: "textures/items/beef_cooked.png",
        name: "Cooked Beef",
        cost: 96,
        data: 0,
        item: "cooked_beef",
    },
    {
        textures: "textures/items/mutton_cooked.png",
        name: "Cooked Mutton",
        cost: 96,
        data: 0,
        item: "cooked_mutton",
    },
    {
        textures: "textures/items/fish_salmon_cooked.png",
        name: "Cooked Salmon",
        cost: 96,
        data: 0,
        item: "cooked_salmon",
    },
    {
        textures: "textures/items/fish_cooked.png",
        name: "Cooked Cod",
        cost: 96,
        data: 0,
        item: "cooked_cod",
    },
];

export const farmCropData = [
    {
        textures: "textures/items/bamboo.png",
        name: "Bamboo",
        cost: 64,
        sell: 4,
        data: 0,
        item: "bamboo",
    },
    {
        textures: "textures/items/reeds.png",
        name: "Sugarcane",
        cost: 64,
        sell: 8,
        data: 0,
        item: "sugar_cane",
    },
    {
        textures: "textures/items/wheat.png",
        name: "Wheat",
        cost: 64,
        sell: 8,
        data: 0,
        item: "wheat",
    },
    {
        textures: "textures/items/beetroot.png",
        name: "Beetroot",
        cost: 64,
        sell: 8,
        data: 0,
        item: "beetroot",
    },
    {
        textures: "textures/items/carrot.png",
        name: "Carrot",
        cost: 64,
        sell: 8,
        data: 0,
        item: "carrot",
    },
    {
        textures: "textures/items/potato.png",
        name: "Potato",
        cost: 128,
        sell: 8,
        data: 0,
        item: "potato",
    },
    {
        textures: "textures/blocks/pumpkin_side.png",
        name: "Pumpkin",
        cost: 128,
        sell: 16,
        data: 0,
        item: "pumpkin",
    },
    {
        textures: "textures/items/melon.png",
        name: "Melon",
        cost: 128,
        sell: 16,
        data: 0,
        item: "melon_slice",
    },
];

export const farmSaplingData = [
    {
        textures: "textures/blocks/sapling_oak.png",
        name: "Oak Sapling",
        cost: 32,
        sell: 8,
        data: 0,
        item: "sapling",
    },
    {
        textures: "textures/blocks/sapling_spruce.png",
        name: "Spruce Sapling",
        cost: 32,
        sell: 8,
        data: 1,
        item: "sapling",
    },
    {
        textures: "textures/blocks/sapling_birch.png",
        name: "Birch Sapling",
        cost: 32,
        sell: 8,
        data: 2,
        item: "sapling",
    },
    {
        textures: "textures/blocks/sapling_jungle.png",
        name: "Jungle Sapling",
        cost: 32,
        sell: 8,
        data: 3,
        item: "sapling",
    },
    {
        textures: "textures/blocks/sapling_acacia.png",
        name: "Acacia Sapling",
        cost: 32,
        sell: 8,
        data: 4,
        item: "sapling",
    },
    {
        textures: "textures/blocks/sapling_roofed_oak.png",
        name: "Dark Oak Sapling",
        cost: 32,
        sell: 8,
        data: 5,
        item: "sapling",
    },
    {
        textures: "textures/items/mangrove_propagule.png",
        name: "Mangrove Propagule",
        cost: 32,
        sell: 8,
        data: 0,
        item: "mangrove_propagule",
    },
    {
        textures: "textures/blocks/warped_fungus.png",
        name: "Warped Fungus",
        cost: 32,
        sell: 8,
        data: 0,
        item: "warped_fungus",
    },
    {
        textures: "textures/blocks/crimson_fungus.png",
        name: "Crimson Fungus",
        cost: 32,
        sell: 8,
        data: 0,
        item: "crimson_fungus",
    },
];

export const farmSeedData = [
    {
        textures: "textures/items/seeds_wheat.png",
        name: "Wheat Seeds",
        cost: 32,
        sell: 4,
        data: 0,
        item: "wheat_seeds",
    },
    {
        textures: "textures/items/seeds_melon.png",
        name: "Melon Seeds",
        cost: 64,
        sell: 4,
        data: 0,
        item: "melon_seeds",
    },
    {
        textures: "textures/items/seeds_beetroot.png",
        name: "Beetroot Seeds",
        cost: 32,
        sell: 4,
        data: 0,
        item: "beetroot_seeds",
    },
    {
        textures: "textures/items/seeds_pumpkin.png",
        name: "Pumpkin Seeds",
        cost: 64,
        sell: 4,
        data: 0,
        item: "pumpkin_seeds",
    },
];

export const miscellaneousData = [
    {
        textures: "textures/items/bread.png",
        name: "Bread",
        cost: 64,
        data: 0,
        item: "bread",
    },
    {
        textures: "textures/items/mushroom_stew.png",
        name: "Mushroom Stew",
        cost: 64,
        data: 0,
        item: "mushroom_stew",
    },
    {
        textures: "textures/items/beetroot_soup.png",
        name: "Beetroot Soup",
        cost: 64,
        data: 0,
        item: "beetroot_soup",
    },
    {
        textures: "textures/items/rabbit_stew.png",
        name: "Rabbit Stew",
        cost: 96,
        data: 0,
        item: "rabbit_stew",
    },
    {
        textures: "textures/items/potato_baked.png",
        name: "Baked Potato",
        cost: 64,
        data: 0,
        item: "baked_potato",
    },
    {
        textures: "textures/items/pumpkin_pie.png",
        name: "Pumpkin Pie",
        cost: 64,
        data: 0,
        item: "pumpkin_pie",
    },
    {
        textures: "textures/items/cookie.png",
        name: "Cookie",
        cost: 32,
        data: 0,
        item: "cookie",
    },
    {
        textures: "textures/items/cake.png",
        name: "Cake",
        cost: 96,
        data: 0,
        item: "cake",
    },
    {
        textures: "textures/items/apple_golden",
        name: "Golden Apple",
        cost: 512,
        data: 0,
        item: "golden_apple",
    },
    {
        textures: "textures/items/apple_golden",
        name: "Ecnhanted Golden Apple",
        cost: 1024,
        data: 0,
        item: "enchanted_golden_apple",
    },
];

export const rawMeatData = [
    {
        textures: "textures/items/chicken_raw.png",
        name: "Raw Chicken",
        cost: 64,
        sell: 8,
        data: 0,
        item: "chicken",
    },
    {
        textures: "textures/items/porkchop_raw.png",
        name: "Raw Porkchop",
        cost: 64,
        sell: 8,
        data: 0,
        item: "porkchop",
    },
    {
        textures: "textures/items/beef_raw.png",
        name: "Raw Beef",
        cost: 64,
        sell: 8,
        data: 0,
        item: "beef",
    },
    {
        textures: "textures/items/mutton_raw.png",
        name: "Raw Mutton",
        cost: 64,
        sell: 8,
        data: 0,
        item: "mutton",
    },
    {
        textures: "textures/items/fish_salmon_raw.png",
        name: "Raw Salmon",
        cost: 64,
        sell: 8,
        data: 0,
        item: "salmon",
    },
    {
        textures: "textures/items/fish_raw.png",
        name: "Raw Cod",
        cost: 64,
        sell: 8,
        data: 0,
        item: "cod",
    },
    {
        textures: "textures/items/fish_clownfish_raw.png",
        name: "Raw Clownfish",
        cost: 64,
        sell: 8,
        data: 0,
        item: "tropical_fish",
    },
];
