export const animalData = [
    {
        textures: "textures/items/egg_glow_squid.png",
        name: "Allay",
        cost: 75000,
        data: 0,
        item: "allay_spawn_egg",
    },
    {
        textures: "textures/items/egg_cat.png",
        name: "Cat",
        cost: 75000,
        data: 0,
        item: "cat_spawn_egg",
    },
    {
        textures: "textures/items/egg_clownfish.png",
        name: "Clownfish",
        cost: 75000,
        data: 0,
        item: "tropical_fish_spawn_egg",
    },
    {
        textures: "textures/items/egg_chicken.png",
        name: "Chicken",
        cost: 75000,
        data: 0,
        item: "chicken_spawn_egg",
    },
    {
        textures: "textures/items/egg_sheep.png",
        name: "Sheep",
        cost: 75000,
        data: 0,
        item: "sheep_spawn_egg",
    },
    {
        textures: "textures/items/egg_cow.png",
        name: "Cow",
        cost: 75000,
        data: 0,
        item: "cow_spawn_egg",
    },
    {
        textures: "textures/items/egg_pig.png",
        name: "Pig",
        cost: 75000,
        data: 0,
        item: "pig_spawn_egg",
    },
    {
        textures: "textures/items/egg_mushroomcow.png",
        name: "Mooshroom",
        cost: 100000,
        data: 0,
        item: "mooshroom_spawn_egg",
    },
    {
        textures: "textures/items/egg_horse.png",
        name: "Horse",
        cost: 75000,
        data: 0,
        item: "horse_spawn_egg",
    },
    {
        textures: "textures/items/egg_parrot.png",
        name: "Parrot",
        cost: 75000,
        data: 0,
        item: "parrot_spawn_egg",
    },
    {
        textures: "textures/items/egg_rabbit.png",
        name: "Rabbit",
        cost: 75000,
        data: 0,
        item: "rabbit_spawn_egg",
    },
    {
        textures: "textures/items/egg_wolf.png",
        name: "Wolf",
        cost: 75000,
        data: 0,
        item: "wolf_spawn_egg",
    },
    {
        textures: "textures/items/egg_panda.png",
        name: "Panda",
        cost: 75000,
        data: 0,
        item: "panda_spawn_egg",
    },
    {
        textures: "textures/items/egg_bee.png",
        name: "Bee",
        cost: 75000,
        data: 0,
        item: "bee_spawn_egg",
    },
    {
        textures: "textures/items/egg_fox.png",
        name: "Fox",
        cost: 75000,
        data: 0,
        item: "fox_spawn_egg",
    },
    {
        textures: "textures/items/egg_polarbear.png",
        name: "Polar Bear",
        cost: 75000,
        data: 0,
        item: "polar_bear_spawn_egg",
    },
    {
        textures: "textures/items/egg_villager.png",
        name: "Villager",
        cost: 150000,
        data: 0,
        item: "villager_spawn_egg",
    },
];

export const spawnerData = [
    {
        textures: "textures/blocks/mob_spawner.png",
        name: "Mob Spawner",
        cost: 120000,
        data: 0,
        item: "mob_spawner",
    },
];

export const undeadData = [
    {
        textures: "textures/items/egg_zombie.png",
        name: "Zombie",
        cost: 85000,
        data: 0,
        item: "zombie_spawn_egg",
    },
    {
        textures: "textures/items/egg_zombievillager.png",
        name: "Zombie Villager",
        cost: 85000,
        data: 0,
        item: "zombie_villager_spawn_egg",
    },
    {
        textures: "textures/items/egg_pigzombie.png",
        name: "Zombie Pigman",
        cost: 85000,
        data: 0,
        item: "zombie_pigman_spawn_egg",
    },
    {
        textures: "textures/items/egg_skeleton.png",
        name: "Skeleton",
        cost: 85000,
        data: 0,
        item: "skeleton_spawn_egg",
    },
    {
        textures: "textures/items/egg_creeper.png",
        name: "Creeper",
        cost: 85000,
        data: 0,
        item: "creeper_spawn_egg",
    },
    {
        textures: "textures/items/egg_spider.png",
        name: "Spider",
        cost: 85000,
        data: 0,
        item: "spider_spawn_egg",
    },
    {
        textures: "textures/items/egg_cave_spider.png",
        name: "Cave Spider",
        cost: 85000,
        data: 0,
        item: "cave_spider_spawn_egg",
    },
    {
        textures: "textures/items/egg_slime.png",
        name: "Slime",
        cost: 85000,
        data: 0,
        item: "slime_spawn_egg",
    },
    {
        textures: "textures/items/egg_enderman.png",
        name: "Enderman",
        cost: 85000,
        data: 0,
        item: "enderman_spawn_egg",
    },
    {
        textures: "textures/items/egg_vindicator.png",
        name: "Vindicator",
        cost: 85000,
        data: 0,
        item: "vindicator_spawn_egg",
    },
    {
        textures: "textures/items/egg_evoker.png",
        name: "Evoker",
        cost: 85000,
        data: 0,
        item: "evoker_spawn_egg",
    },
    {
        textures: "textures/items/egg_pillager.png",
        name: "Pillager",
        cost: 85000,
        data: 0,
        item: "pillager_spawn_egg",
    },
    {
        textures: "textures/items/egg_ravager.png",
        name: "Ravager",
        cost: 85000,
        data: 0,
        item: "ravager_spawn_egg",
    },
    {
        textures: "textures/items/egg_wither.png",
        name: "Wither Skeleton",
        cost: 85000,
        data: 0,
        item: "wither_skeleton_spawn_egg",
    },
];
