export const axeData = [
    {
        textures: "textures/items/wood_axe",
        name: "Wooden Axe",
        cost: 256,
        data: 0,
        item: "wooden_axe",
    },
    {
        textures: "textures/items/stone_axe",
        name: "Stone Axe",
        cost: 512,
        data: 0,
        item: "stone_axe",
    },
    {
        textures: "textures/items/iron_axe",
        name: "Iron Axe",
        cost: 2048,
        data: 0,
        item: "iron_axe",
    },
    {
        textures: "textures/items/gold_axe",
        name: "Golden Axe",
        cost: 1536,
        data: 0,
        item: "golden_axe",
    },
    {
        textures: "textures/items/diamond_axe",
        name: "Diamond Axe",
        cost: 2560,
        data: 0,
        item: "diamond_axe",
    },
    {
        textures: "textures/items/netherite_axe",
        name: "Netherite Axe",
        cost: 3200,
        data: 0,
        item: "netherite_axe",
    },
];

export const bootsData = [
    {
        textures: "textures/items/leather_boots",
        name: "Leather Boots",
        cost: 128,
        data: 0,
        item: "leather_boots",
    },
    {
        textures: "textures/items/chainmail_boots",
        name: "Chain Boots",
        cost: 256,
        data: 0,
        item: "chainmail_boots",
    },
    {
        textures: "textures/items/iron_boots",
        name: "Iron Boots",
        cost: 1024,
        data: 0,
        item: "iron_boots",
    },
    {
        textures: "textures/items/gold_boots",
        name: "Gold Boots",
        cost: 768,
        data: 0,
        item: "gold_boots",
    },
    {
        textures: "textures/items/diamond_boots",
        name: "Diamond Boots",
        cost: 1280,
        data: 0,
        item: "diamond_boots",
    },
    {
        textures: "textures/items/netherite_boots",
        name: "Netherite Boots",
        cost: 1600,
        data: 0,
        item: "netherite_boots",
    },
];

export const chestplateData = [
    {
        textures: "textures/items/leather_chestplate",
        name: "Leather Chestplate",
        cost: 384,
        data: 0,
        item: "leather_chestplate",
    },
    {
        textures: "textures/items/chainmail_chestplate",
        name: "Chain Chestplate",
        cost: 768,
        data: 0,
        item: "chainmail_chestplate",
    },
    {
        textures: "textures/items/iron_chestplate",
        name: "Iron Chestplate",
        cost: 3072,
        data: 0,
        item: "iron_chestplate",
    },
    {
        textures: "textures/items/gold_chestplate",
        name: "Gold Chestplate",
        cost: 2304,
        data: 0,
        item: "gold_chestplate",
    },
    {
        textures: "textures/items/diamond_chestplate",
        name: "Diamond Chestplate",
        cost: 3840,
        data: 0,
        item: "diamond_chestplate",
    },
    {
        textures: "textures/items/netherite_chestplate",
        name: "Netherite Chestplate",
        cost: 4800,
        data: 0,
        item: "netherite_chestplate",
    },
];

export const helmetData = [
    {
        textures: "textures/items/leather_helmet",
        name: "Leather Helmet",
        cost: 128,
        data: 0,
        item: "leather_helmet",
    },
    {
        textures: "textures/items/chainmail_helmet",
        name: "Chain Helmet",
        cost: 256,
        data: 0,
        item: "chainmail_helmet",
    },
    {
        textures: "textures/items/iron_helmet",
        name: "Iron Helmet",
        cost: 1024,
        data: 0,
        item: "iron_helmet",
    },
    {
        textures: "textures/items/gold_helmet",
        name: "Gold Helmet",
        cost: 768,
        data: 0,
        item: "gold_helmet",
    },
    {
        textures: "textures/items/diamond_helmet",
        name: "Diamond Helmet",
        cost: 1280,
        data: 0,
        item: "diamond_helmet",
    },
    {
        textures: "textures/items/netherite_helmet",
        name: "Netherite Helmet",
        cost: 1600,
        data: 0,
        item: "netherite_helmet",
    },
];

export const hoeData = [
    {
        textures: "textures/items/wood_hoe",
        name: "Wooden Hoe",
        cost: 256,
        data: 0,
        item: "wooden_hoe",
    },
    {
        textures: "textures/items/stone_hoe",
        name: "Stone Hoe",
        cost: 512,
        data: 0,
        item: "stone_hoe",
    },
    {
        textures: "textures/items/iron_hoe",
        name: "Iron Hoe",
        cost: 2048,
        data: 0,
        item: "iron_hoe",
    },
    {
        textures: "textures/items/gold_hoe",
        name: "Golden Hoe",
        cost: 1536,
        data: 0,
        item: "golden_hoe",
    },
    {
        textures: "textures/items/diamond_hoe",
        name: "Diamond Hoe",
        cost: 2560,
        data: 0,
        item: "diamond_hoe",
    },
    {
        textures: "textures/items/netherite_hoe",
        name: "Netherite Hoe",
        cost: 3200,
        data: 0,
        item: "netherite_hoe",
    },
];

export const leggingsData = [
    {
        textures: "textures/items/leather_leggings",
        name: "Leather Leggings",
        cost: 256,
        data: 0,
        item: "leather_leggings",
    },
    {
        textures: "textures/items/chainmail_leggings",
        name: "Chain Leggings",
        cost: 512,
        data: 0,
        item: "chainmail_leggings",
    },
    {
        textures: "textures/items/iron_leggings",
        name: "Iron Leggings",
        cost: 2048,
        data: 0,
        item: "iron_leggings",
    },
    {
        textures: "textures/items/gold_leggings",
        name: "Gold Leggings",
        cost: 1536,
        data: 0,
        item: "gold_leggings",
    },
    {
        textures: "textures/items/diamond_leggings",
        name: "Diamond Leggings",
        cost: 2560,
        data: 0,
        item: "diamond_leggings",
    },
    {
        textures: "textures/items/netherite_leggings",
        name: "Netherite Leggings",
        cost: 3200,
        data: 0,
        item: "netherite_leggings",
    },
];

export const pickaxeData = [
    {
        textures: "textures/items/wood_pickaxe",
        name: "Wooden Pickaxe",
        cost: 256,
        data: 0,
        item: "wooden_pickaxe",
    },
    {
        textures: "textures/items/stone_pickaxe",
        name: "Stone Pickaxe",
        cost: 512,
        data: 0,
        item: "stone_pickaxe",
    },
    {
        textures: "textures/items/iron_pickaxe",
        name: "Iron Pickaxe",
        cost: 2048,
        data: 0,
        item: "iron_pickaxe",
    },
    {
        textures: "textures/items/gold_pickaxe",
        name: "Golden Pickaxe",
        cost: 1536,
        data: 0,
        item: "golden_pickaxe",
    },
    {
        textures: "textures/items/diamond_pickaxe",
        name: "Diamond Pickaxe",
        cost: 2560,
        data: 0,
        item: "diamond_pickaxe",
    },
    {
        textures: "textures/items/netherite_pickaxe",
        name: "Netherite Pickaxe",
        cost: 3200,
        data: 0,
        item: "netherite_pickaxe",
    },
];

export const shovelData = [
    {
        textures: "textures/items/wood_shovel",
        name: "Wooden Shovel",
        cost: 256,
        data: 0,
        item: "wooden_shovel",
    },
    {
        textures: "textures/items/stone_shovel",
        name: "Stone Shovel",
        cost: 512,
        data: 0,
        item: "stone_shovel",
    },
    {
        textures: "textures/items/iron_shovel",
        name: "Iron Shovel",
        cost: 2048,
        data: 0,
        item: "iron_shovel",
    },
    {
        textures: "textures/items/gold_shovel",
        name: "Golden Shovel",
        cost: 1536,
        data: 0,
        item: "golden_shovel",
    },
    {
        textures: "textures/items/diamond_shovel",
        name: "Diamond Shovel",
        cost: 2560,
        data: 0,
        item: "diamond_shovel",
    },
    {
        textures: "textures/items/netherite_shovel",
        name: "Netherite Shovel",
        cost: 3200,
        data: 0,
        item: "netherite_shovel",
    },
];

export const swordData = [
    {
        textures: "textures/items/wood_sword",
        name: "Wooden Sword",
        cost: 256,
        data: 0,
        item: "wooden_sword",
    },
    {
        textures: "textures/items/stone_sword",
        name: "Stone Sword",
        cost: 512,
        data: 0,
        item: "stone_sword",
    },
    {
        textures: "textures/items/iron_sword",
        name: "Iron Sword",
        cost: 2048,
        data: 0,
        item: "iron_sword",
    },
    {
        textures: "textures/items/gold_sword",
        name: "Golden Sword",
        cost: 1536,
        data: 0,
        item: "golden_sword",
    },
    {
        textures: "textures/items/diamond_sword",
        name: "Diamond Sword",
        cost: 2560,
        data: 0,
        item: "diamond_sword",
    },
    {
        textures: "textures/items/netherite_sword",
        name: "Netherite Sword",
        cost: 3200,
        data: 0,
        item: "netherite_sword",
    },
];

export const utilitiesData = [
    {
        textures: "textures/items/elytra",
        name: "Elytra",
        cost: 20480,
        data: 0,
        item: "elytra",
    },
    {
        textures: "textures/items/fireworks",
        name: "Firework Rocket",
        cost: 128,
        data: 0,
        item: "firework_rocket",
    },
    {
        textures: "textures/items/name_tag",
        name: "Name Tag",
        cost: 1000,
        data: 0,
        item: "name_tag",
    },
    {
        textures: "textures/items/bucket_empty",
        name: "Bucket",
        cost: 128,
        data: 0,
        item: "bucket",
    },
    {
        textures: "textures/items/bucket_water",
        name: "Water Bucket",
        cost: 196,
        data: 0,
        item: "water_bucket",
    },
    {
        textures: "textures/items/bucket_lava",
        name: "Lava Bucket",
        cost: 512,
        data: 0,
        item: "lava_bucket",
    },
    {
        textures: "textures/items/bucket_powder_snow",
        name: "Snow Powder Bucket",
        cost: 768,
        data: 0,
        item: "snow_powder_bucket",
    },
    {
        textures: "textures/items/fishing_rod_uncast",
        name: "Fishing Rod",
        cost: 196,
        data: 0,
        item: "fishing_rod",
    },
    {
        textures: "textures/items/carrot_on_a_stick",
        name: "Carrot on Stick",
        cost: 256,
        data: 0,
        item: "carrot_on_a_stick",
    },
    {
        textures: "textures/items/warped_fungus_on_a_stick",
        name: "Warped Fungus on Stick",
        cost: 256,
        data: 0,
        item: "warped_fungus_on_a_stick",
    },
    {
        textures: "textures/items/flint_and_steel",
        name: "Flint and Steel",
        cost: 128,
        data: 0,
        item: "flint_and_steel",
    },
    {
        textures: "textures/items/fireball",
        name: "Fire Charge",
        cost: 384,
        data: 0,
        item: "fire_charge",
    },
    {
        textures: "textures/items/shears",
        name: "Shears",
        cost: 256,
        data: 0,
        item: "shears",
    },
    {
        textures: "textures/items/lead",
        name: "Lead",
        cost: 256,
        data: 0,
        item: "lead",
    },
    {
        textures: "textures/items/compass_item",
        name: "Compass",
        cost: 512,
        data: 0,
        item: "compass",
    },
    {
        textures: "textures/items/recovery_compass_item",
        name: "Recovery Compass",
        cost: 1024,
        data: 0,
        item: "recovery_compass",
    },
    {
        textures: "textures/items/clock_item",
        name: "Clock",
        cost: 256,
        data: 0,
        item: "clock",
    },
    {
        textures: "textures/items/spyglass",
        name: "Spyglass",
        cost: 768,
        data: 0,
        item: "spyglass",
    },
    {
        textures: "textures/items/map_empty",
        name: "Empty Map",
        cost: 384,
        data: 0,
        item: "empty_map",
    },
    {
        textures: "textures/items/book_writable",
        name: "Book & Quill",
        cost: 256,
        data: 0,
        item: "writable_book",
    },
    {
        textures: "textures/items/saddle",
        name: "Saddle",
        cost: 512,
        data: 0,
        item: "saddle",
    },
];
