export const bottleData = [
    {
        textures: "textures/items/potion_bottle_nightVision",
        name: "Night Vision (8:00)",
        cost: 512,
        data: 6,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_invisibility",
        name: "Invisibility (8:00)",
        cost: 512,
        data: 8,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_jump",
        name: "Jump Boost (8:00)",
        cost: 512,
        data: 10,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_fireResistance",
        name: "Fire Resistance (8:00)",
        cost: 512,
        data: 13,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_digSpeed",
        name: "Speed (8:00)",
        cost: 512,
        data: 15,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_waterBreathing",
        name: "Water Breathing (8:00)",
        cost: 512,
        data: 20,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_damageBoost",
        name: "Strength (8:00)",
        cost: 512,
        data: 32,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_slowFall",
        name: "Slow Falling (4:00)",
        cost: 512,
        data: 41,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_regeneration",
        name: "Regeneration (2:00)",
        cost: 512,
        data: 29,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_heal",
        name: "Instant Health II",
        cost: 768,
        data: 22,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_harm",
        name: "Instant Damage II",
        cost: 768,
        data: 24,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_digSlowdown",
        name: "Slowness (4:00)",
        cost: 512,
        data: 18,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_weakness",
        name: "Weakness (4:00)",
        cost: 512,
        data: 35,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_poison",
        name: "Poison (2:00)",
        cost: 512,
        data: 26,
        item: "potion",
    },
    {
        textures: "textures/items/potion_bottle_wither",
        name: "Decay (0:40)",
        cost: 512,
        data: 36,
        item: "potion",
    },
];

export const lingeringData = [
    {
        textures: "textures/items/potion_bottle_lingering_nightVision",
        name: "Night Vision (2:00)",
        cost: 512,
        data: 6,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_invisibility",
        name: "Invisibility (2:00)",
        cost: 512,
        data: 8,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_jump",
        name: "Jump Boost (2:00)",
        cost: 512,
        data: 10,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_fireResistance",
        name: "Fire Resistance (2:00)",
        cost: 512,
        data: 13,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_digSpeed",
        name: "Speed (2:00)",
        cost: 512,
        data: 15,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_waterBreathing",
        name: "Water Breathing (2:00)",
        cost: 512,
        data: 20,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_damageBoost",
        name: "Strength (2:00)",
        cost: 512,
        data: 32,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_slowFall",
        name: "Slow Falling (1:00)",
        cost: 512,
        data: 41,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_regeneration",
        name: "Regeneration (0:30)",
        cost: 512,
        data: 29,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_heal",
        name: "Instant Health II",
        cost: 768,
        data: 22,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_harm",
        name: "Instant Damage II",
        cost: 768,
        data: 24,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_digSlowdown",
        name: "Slowness (1:00)",
        cost: 512,
        data: 18,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_weakness",
        name: "Weakness (1:00)",
        cost: 512,
        data: 35,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_poison",
        name: "Poison (0:30)",
        cost: 512,
        data: 26,
        item: "lingering_potion",
    },
    {
        textures: "textures/items/potion_bottle_lingering_wither",
        name: "Decay (0:10)",
        cost: 512,
        data: 36,
        item: "lingering_potion",
    },
];

export const splashData = [
    {
        textures: "textures/items/potion_bottle_splash_nightVision",
        name: "Night Vision (6:00)",
        cost: 512,
        data: 6,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_invisibility",
        name: "Invisibility (6:00)",
        cost: 512,
        data: 8,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_jump",
        name: "Jump Boost (6:00)",
        cost: 512,
        data: 10,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_fireResistance",
        name: "Fire Resistance (6:00)",
        cost: 512,
        data: 13,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_digSpeed",
        name: "Speed (6:00)",
        cost: 512,
        data: 15,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_waterBreathing",
        name: "Water Breathing (6:00)",
        cost: 512,
        data: 20,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_damageBoost",
        name: "Strength (6:00)",
        cost: 512,
        data: 32,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_slowFall",
        name: "Slow Falling (3:00)",
        cost: 512,
        data: 41,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_regeneration",
        name: "Regeneration (1:30)",
        cost: 512,
        data: 29,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_heal",
        name: "Instant Health II",
        cost: 768,
        data: 22,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_harm",
        name: "Instant Damage II",
        cost: 768,
        data: 24,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_digSlowdown",
        name: "Slowness (3:00)",
        cost: 512,
        data: 18,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_weakness",
        name: "Weakness (3:00)",
        cost: 512,
        data: 35,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_poison",
        name: "Poison (1:30)",
        cost: 512,
        data: 26,
        item: "splash_potion",
    },
    {
        textures: "textures/items/potion_bottle_splash_wither",
        name: "Decay (0:30)",
        cost: 512,
        data: 36,
        item: "splash_potion",
    },
];
